# Generated by Django 2.0.4 on 2018-04-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20180407_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendition',
            name='focal_point_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='rendition',
            unique_together={('image', 'filter_spec', 'focal_point_key')},
        ),
    ]
